name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       REGISTRY_NAME: pwcinfradockerrg
       IMAGE_NAME: springboot-petclinic-actions
       TAGS: v5
       HELM_EXPERIMENTAL_OCI: 1
       HELM_VERSION_TO_INSTALL: 3.5.0
       ACR_REPO_NAME: springboot/petclinic

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # exection permission
    - name: adding execution mode 
      run: chmod +x mvnw
    - name: Build with Maven Wrapper
      run: ./mvnw clean install
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: change to server directory and build
      run: |-
        cd spring-petclinic-server ; 
        mvn clean package docker:build
    
    # - name: Docker GCP credential helper in cmd
    #   run: |
    #      gcloud auth configure-docker -q

    - name: tagging the image to push to ACR
      run: |-
        docker tag $IMAGE_NAME ${{ env.REGISTRY_NAME }}.azurecr.io/$IMAGE_NAME:$TAGS
     
    - name: Push image to ACR
      run: |-
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/$IMAGE_NAME:$TAGS

    - name: install helm
      uses: Azure/setup-helm@v1
      with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }} # default is latest

    - name: login to acr using helm
      run: |
        helm registry login ${{ env.REGISTRY_NAME }}.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Helm Repo Add
      run: |
        helm repo add ${{ env.REGISTRY_NAME }} https://${{ env.REGISTRY_NAME }}/helm/v1/repo --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
      env:
        HELM_EXPERIMENTAL_OCI: 1

    - name: save helm chart to local registry
      run: |
        cd .\charts\petclinic
        helm chart save . ${{ env.IMAGE_NAME }}:v${{ github.run_id }}
        helm chart save . ${{ env.REGISTRY_NAME }}/helm/${{ env.IMAGE_NAME }}:v${{ github.run_id }}
        helm chart list
      env:
        HELM_EXPERIMENTAL_OCI: 1
      
    - name: publish chart to acr
      run: |
        helm chart push ${{ env.REGISTRY_NAME }}/helm/${{ env.IMAGE_NAME }}:v${{ github.run_id }}
      env:
        HELM_EXPERIMENTAL_OCI: 1
